export { CartIcon } from '@/components/icons/cartIcon'
export { PlusIcon } from '@/components/icons/plusIcon'
export { MinusIcon } from '@/components/icons/minusIcon'
export { ArrowRight } from '@/components/icons/arrowRight'
export { ArrowNavigate} from '@/components/icons/arrowNavigate'
export { CloseIcon } from '@/components/icons/closeIcon'
export { MinicartIcon } from '@/components/icons/minicartIcon'
export { TrashIcon } from '@/components/icons/trashIcon'